### ISSUE TITLE
Support sync multiple ports to routing api per services

### ISSUE THREAD

**Issue by jiangytcn** [pivotal-cf-experimental/kubo-release#51]
The route-sync only sync the first exported port of the k8s service, either tcp-route-sync or http-route-sync, but if the k8s service has two exported ports, only the first port synced to the CF routing service. It'll be more reasonable to sync all exported ports.
BTW, is there any channel to keep track of the project status and collaborate with you guys ?

**Comment by johnsonj** [comment]
Thanks @jiangytcn, we put this limitation in place because it was easy so this is a great suggestion. If you need a workaround you can deploy a service per port needed.

We'll discuss this in our meeting tomorrow but likely we can slate this for v0.0.5. If you're interested in getting this landed sooner I'm happy to review your ideas/a PR.

In terms of communicating with the team, GitHub is the way for now. We've applied to move to the Cloud Foundry org via [CF-Extensions](https://docs.google.com/document/d/1ZOFD5nBQC_vh9CmKHOGT7ugtNaJQ1t03jkLVsyDOH6k/edit#heading=h.clyzsnbh7edl) and will have a slack channel to go along with it.

**Comment by jiangytcn** [comment]
Thank you @johnsonj . I'll split the service per port

**Comment by alejandrogoyen** [comment]
Hi @jiangytcn we have created #kubo channel in CloudFoundry slack

https://slack.cloudfoundry.org/
